const colors = {
  light: {
    text: "#ffffff",
    tint: "#8B5CF6",
    background: "#0F0F1A",
    foreground: "#ffffff",
    card: "#1A1A2E",
    cardForeground: "#ffffff",
    primary: "#8B5CF6",
    primaryForeground: "#ffffff",
    secondary: "#1E1E36",
    secondaryForeground: "#E0E0FF",
    muted: "#252540",
    mutedForeground: "#9CA3AF",
    accent: "#06B6D4",
    accentForeground: "#ffffff",
    destructive: "#EF4444",
    destructiveForeground: "#ffffff",
    border: "#2A2A45",
    input: "#252540",
  },
  dark: {
    text: "#ffffff",
    tint: "#8B5CF6",
    background: "#0F0F1A",
    foreground: "#ffffff",
    card: "#1A1A2E",
    cardForeground: "#ffffff",
    primary: "#8B5CF6",
    primaryForeground: "#ffffff",
    secondary: "#1E1E36",
    secondaryForeground: "#E0E0FF",
    muted: "#252540",
    mutedForeground: "#9CA3AF",
    accent: "#06B6D4",
    accentForeground: "#ffffff",
    destructive: "#EF4444",
    destructiveForeground: "#ffffff",
    border: "#2A2A45",
    input: "#252540",
  },
  radius: 16,
};

export default colors;
